/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhysicsRouteImport } from './routes/physics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutExperimentsRouteImport } from './routes/_layout/experiments'
import { Route as LayoutComponentsRouteImport } from './routes/_layout/components'
import { Route as LayoutCardsRouteImport } from './routes/_layout/cards'
import { Route as LayoutExperimentsPhysicsPlaygroundRouteImport } from './routes/_layout/experiments/physics-playground'

const PhysicsRoute = PhysicsRouteImport.update({
  id: '/physics',
  path: '/physics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExperimentsRoute = LayoutExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutComponentsRoute = LayoutComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCardsRoute = LayoutCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExperimentsPhysicsPlaygroundRoute =
  LayoutExperimentsPhysicsPlaygroundRouteImport.update({
    id: '/physics-playground',
    path: '/physics-playground',
    getParentRoute: () => LayoutExperimentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/physics': typeof PhysicsRoute
  '/cards': typeof LayoutCardsRoute
  '/components': typeof LayoutComponentsRoute
  '/experiments': typeof LayoutExperimentsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/experiments/physics-playground': typeof LayoutExperimentsPhysicsPlaygroundRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/physics': typeof PhysicsRoute
  '/cards': typeof LayoutCardsRoute
  '/components': typeof LayoutComponentsRoute
  '/experiments': typeof LayoutExperimentsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/experiments/physics-playground': typeof LayoutExperimentsPhysicsPlaygroundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/physics': typeof PhysicsRoute
  '/_layout/cards': typeof LayoutCardsRoute
  '/_layout/components': typeof LayoutComponentsRoute
  '/_layout/experiments': typeof LayoutExperimentsRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/experiments/physics-playground': typeof LayoutExperimentsPhysicsPlaygroundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/physics'
    | '/cards'
    | '/components'
    | '/experiments'
    | '/'
    | '/experiments/physics-playground'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/physics'
    | '/cards'
    | '/components'
    | '/experiments'
    | '/'
    | '/experiments/physics-playground'
  id:
    | '__root__'
    | '/_layout'
    | '/auth'
    | '/physics'
    | '/_layout/cards'
    | '/_layout/components'
    | '/_layout/experiments'
    | '/_layout/'
    | '/_layout/experiments/physics-playground'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
  PhysicsRoute: typeof PhysicsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/physics': {
      id: '/physics'
      path: '/physics'
      fullPath: '/physics'
      preLoaderRoute: typeof PhysicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/experiments': {
      id: '/_layout/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof LayoutExperimentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/components': {
      id: '/_layout/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof LayoutComponentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cards': {
      id: '/_layout/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof LayoutCardsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/experiments/physics-playground': {
      id: '/_layout/experiments/physics-playground'
      path: '/physics-playground'
      fullPath: '/experiments/physics-playground'
      preLoaderRoute: typeof LayoutExperimentsPhysicsPlaygroundRouteImport
      parentRoute: typeof LayoutExperimentsRoute
    }
  }
}

interface LayoutExperimentsRouteChildren {
  LayoutExperimentsPhysicsPlaygroundRoute: typeof LayoutExperimentsPhysicsPlaygroundRoute
}

const LayoutExperimentsRouteChildren: LayoutExperimentsRouteChildren = {
  LayoutExperimentsPhysicsPlaygroundRoute:
    LayoutExperimentsPhysicsPlaygroundRoute,
}

const LayoutExperimentsRouteWithChildren =
  LayoutExperimentsRoute._addFileChildren(LayoutExperimentsRouteChildren)

interface LayoutRouteChildren {
  LayoutCardsRoute: typeof LayoutCardsRoute
  LayoutComponentsRoute: typeof LayoutComponentsRoute
  LayoutExperimentsRoute: typeof LayoutExperimentsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCardsRoute: LayoutCardsRoute,
  LayoutComponentsRoute: LayoutComponentsRoute,
  LayoutExperimentsRoute: LayoutExperimentsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRoute,
  PhysicsRoute: PhysicsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
